version: '3.9'

services:
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${PASSWORD_DB}
    env_file:
      - .env
    volumes:
      - ./docker/postgres/init.sh:/docker-entrypoint-init.d/init.sh
      - ./docker/db:/var/lib/postgresql/data/
    ports:
      - "5436:5432"
    restart: always
  app:
      build:
        context: .
        dockerfile: Dockerfile
      # command: /go/notes
      # TODO: debug
      command:
        - /bin/bash
        - '-c'
        - go run cmd/app/main.go
      volumes:
        - .:/app
      ports:
        - 8080:8080
      env_file:
        - .env
      depends_on:
        - db